apiVersion: apps/v1
kind: Deployment
metadata:
  name: technova-ms-product
  namespace: technova
  labels:
    app: technova-ms-product
spec:
  replicas: 3
  selector:
    matchLabels:
      app: technova-ms-product
  template:
    metadata:
      labels:
        app: technova-ms-product
    spec:
      containers:
        - name: technova-ms-product
          image: gwrgwr/technova-ms-product:latest
          ports:
            - containerPort: 8080
          env:
            - name: MONGODB_URI_MS_PRODUCT
              valueFrom:
                secretKeyRef:
                  name: mongodb-ms-product
                  key: MONGODB_URI_MS_PRODUCT
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: username
            - name: RABBITMQ_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: password
            - name: RABBITMQ_HOST
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: host